[[permission]]
identifier = "allow-commands"
description = "Allows all app commands"
commands.allow = [
    "init_vault",
    "vault_save",
    "vault_load",
    "connect_network",
    "disconnect_network",
    "revoke_session_token",
    "reset_database",
    "vault_exists",
    "export_database",
    "import_database",
    "signal_init",
    "signal_sync_keys",
    "signal_encrypt",
    "set_panic_password",
    "vault_delete_media",
    "vault_export_media",
    "signal_sign_message",
    "signal_set_peer_trust",
    "signal_get_identity_hash",
    "signal_get_fingerprint",
    "send_typing_status",
    "send_receipt",
    "send_profile_update",
    "open_file",
    "db_get_messages",
    "db_search_messages",
    "db_update_messages",
    "db_upsert_chat",
    "db_reset_unread_count",
    "db_get_chats",
    "db_get_contacts",
    "db_set_contact_blocked",
    "db_set_contact_nickname",
    "db_delete_messages",
    "db_delete_chat",
    "db_set_chat_pinned",
    "db_set_chat_archived",
    "db_get_starred_messages",
    "db_get_message_offset",
    "register_nickname",
    "burn_account",
    "process_outgoing_text",
    "process_outgoing_group_text",
    "process_outgoing_media",
    "process_outgoing_group_media",
    "create_group",
    "add_to_group",
    "leave_group",
    "nickname_lookup",
    "identity_resolve",
    "db_set_contact_global_nickname",
    "update_group_name",
    "get_media_proxy_port",
    "vault_retry_bridge"
]

[[set]]
identifier = "default"
description = "Default permission set"
permissions = ["allow-commands"]