[[permission]]
identifier = "allow-commands"
description = "Allows all app commands"
commands.allow = [
    "init_vault",
    "vault_save",
    "vault_load",
    "crypto_sha256",
    "signal_decrypt_media",
    "connect_network",
    "disconnect_network",
    "send_to_network",
    "flush_outbox",
    "reset_database",
    "crypto_mine_pow",
    "vault_exists",
    "start_native_recording",
    "stop_native_recording",
    "save_file",
    "export_database",
    "import_database",
    "signal_init",
    "signal_sync_keys",
    "signal_encrypt",
    "set_panic_password",
    "vault_save_media",
    "vault_load_media",
    "vault_delete_media",
    "signal_sign_message",
    "signal_set_peer_trust",
    "signal_get_identity_hash",
    "signal_get_fingerprint",
    "send_typing_status",
    "send_receipt",
    "send_profile_update",
    "open_file",
    "db_save_message",
    "db_get_messages",
    "db_search_messages",
    "db_update_messages",
    "db_upsert_chat",
    "db_get_chats",
    "db_get_contacts",
    "db_set_contact_blocked",
    "db_set_contact_nickname",
    "db_delete_messages",
    "db_delete_chat",
    "db_set_chat_pinned",
    "db_set_chat_archived",
    "db_get_starred_messages",
    "db_export_media",
    "register_nickname",
    "burn_account",
    "process_outgoing_text",
    "process_outgoing_media",
    "write_temp_media",
    "signal_get_own_identity",
    "signal_get_peer_identity",
    "crypto_encrypt_media",
    "crypto_encrypt_file",
    "crypto_decrypt_media",
    "crypto_sha256"
]

[[set]]
identifier = "default"
description = "Default permission set"
permissions = ["allow-commands"]